#' @name data_TGP
#'
#' @docType data
#'
#' @title Sample data from the 1000 Genomes Project
#'
#' @description The 1000 Genomes Project (TGP) created a catalogue of common
#'     human genetic variation, using openly consented samples from people
#'     who declared themselves to be healthy. The reference data resources
#'     generated by the project remain heavily used by the biomedical
#'     science community. The International Genome Sample Resource (IGSR)
#'     maintains and shares the human genetic variation resources built
#'     by the 1000 Genomes Project. We also update the resources to the
#'     current reference assembly, add new data sets generated from the 1000
#'     Genomes Project samples and add data from projects working with other
#'     openly consented samples.
#'
#' @format \code{data_TGP} is a 1092 x 50000 matrix.
#'
#' @source \url{https://www.internationalgenome.org/}
NULL
