# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_AwesomePackage_rcpp_hello_world', PACKAGE = 'AwesomePackage')
}

rcpp_psd_fit_em <- function(P, F, G, epsilon, maxiter) {
    .Call('_AwesomePackage_rcpp_psd_fit_em', PACKAGE = 'AwesomePackage', P, F, G, epsilon, maxiter)
}

rcpp_psd_fit_sqp <- function(P, F, G, epsilon, maxiter, zero) {
    .Call('_AwesomePackage_rcpp_psd_fit_sqp', PACKAGE = 'AwesomePackage', P, F, G, epsilon, maxiter, zero)
}

rcpp_update_pp <- function(G, ZP, ZaF, ZbF, ALPHA) {
    .Call('_AwesomePackage_rcpp_update_pp', PACKAGE = 'AwesomePackage', G, ZP, ZaF, ZbF, ALPHA)
}

rcpp_update_ff <- function(G, ZP, ZaF, ZbF, BETAa, BETAb) {
    .Call('_AwesomePackage_rcpp_update_ff', PACKAGE = 'AwesomePackage', G, ZP, ZaF, ZbF, BETAa, BETAb)
}

rcpp_marginal_likelihood_e1 <- function(G, ZP, ZaF, ZbF) {
    .Call('_AwesomePackage_rcpp_marginal_likelihood_e1', PACKAGE = 'AwesomePackage', G, ZP, ZaF, ZbF)
}

