# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_AwesomePackage_rcpp_hello_world', PACKAGE = 'AwesomePackage')
}

rcpp_update_p_em <- function(G, P, F) {
    .Call('_AwesomePackage_rcpp_update_p_em', PACKAGE = 'AwesomePackage', G, P, F)
}

rcpp_update_f_em <- function(G, P, F) {
    .Call('_AwesomePackage_rcpp_update_f_em', PACKAGE = 'AwesomePackage', G, P, F)
}

rcpp_psd_loss <- function(G, P, F) {
    .Call('_AwesomePackage_rcpp_psd_loss', PACKAGE = 'AwesomePackage', G, P, F)
}

rcpp_update_p_sqp <- function(G, P, F, zero) {
    .Call('_AwesomePackage_rcpp_update_p_sqp', PACKAGE = 'AwesomePackage', G, P, F, zero)
}

rcpp_update_f_sqp <- function(G, P, F, zero) {
    .Call('_AwesomePackage_rcpp_update_f_sqp', PACKAGE = 'AwesomePackage', G, P, F, zero)
}

rcpp_update_pp_svi <- function(G, PP, ZP, ZaF, ZbF, ALPHA, J, rho) {
    .Call('_AwesomePackage_rcpp_update_pp_svi', PACKAGE = 'AwesomePackage', G, PP, ZP, ZaF, ZbF, ALPHA, J, rho)
}

rcpp_update_zp <- function(PP) {
    .Call('_AwesomePackage_rcpp_update_zp', PACKAGE = 'AwesomePackage', PP)
}

rcpp_update_zf <- function(FFa, FFb) {
    .Call('_AwesomePackage_rcpp_update_zf', PACKAGE = 'AwesomePackage', FFa, FFb)
}

rcpp_update_pp <- function(G, ZP, ZaF, ZbF, ALPHA) {
    .Call('_AwesomePackage_rcpp_update_pp', PACKAGE = 'AwesomePackage', G, ZP, ZaF, ZbF, ALPHA)
}

rcpp_update_ff <- function(G, ZP, ZaF, ZbF, BETAa, BETAb) {
    .Call('_AwesomePackage_rcpp_update_ff', PACKAGE = 'AwesomePackage', G, ZP, ZaF, ZbF, BETAa, BETAb)
}

rcpp_marginal_likelihood_e1 <- function(G, ZP, ZaF, ZbF) {
    .Call('_AwesomePackage_rcpp_marginal_likelihood_e1', PACKAGE = 'AwesomePackage', G, ZP, ZaF, ZbF)
}

