# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('_AwesomePackage_rcpp_hello_world', PACKAGE = 'AwesomePackage')
}

rcpp_psd_fit_em <- function(P, F, G, maxiter) {
    .Call('_AwesomePackage_rcpp_psd_fit_em', PACKAGE = 'AwesomePackage', P, F, G, maxiter)
}

